#!sage -python
# EASY-INSTALL-ENTRY-SCRIPT: 'pylint==1.9.5','console_scripts','pylint'
__requires__ = 'pylint==1.9.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pylint==1.9.5', 'console_scripts', 'pylint')()
    )
